# Generated by Django 5.0.6 on 2026-08-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(db_index=True, max_length=80)),
                ('certificate_date', models.DateField()),
                ('responsible', models.CharField(max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='equipment/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-certificate_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('CALIBRATION', 'Calibración')], default='PREVENTIVE', max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('activity', models.TextField()),
            ],
            options={
                'ordering': ['instruction_type', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('CALIBRATION', 'Calibración'), ('INSTALLATION', 'Instalación'), ('INSPECTION', 'Inspección')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('report', models.FileField(blank=True, upload_to='equipment/orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spare_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Fotografía'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento'), ('AUDIO', 'Audio')], max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, upload_to='equipment/evidence/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('expected_value', models.CharField(max_length=100)),
                ('measured_value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('passed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('ENGINEER', 'Engineer'), ('CLIENT', 'Client'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('signed_by', models.CharField(max_length=150)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('asset_tag', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Placa / código de inventario')),
                ('serial', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Serie')),
                ('internal_code', models.CharField(blank=True, max_length=50, verbose_name='Código N.T.')),
                ('software_identifier', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Identificador Software (Id)')),
                ('branch_text', models.CharField(blank=True, help_text='Útil si la marca no existe en catálogo.', max_length=120, verbose_name='Marca (texto)')),
                ('technology_type', models.CharField(blank=True, choices=[('ELECTRONIC', 'Electrónico'), ('ELECTROMEDICAL', 'Electromédico'), ('MECHANICAL', 'Mecánico'), ('MIXED', 'Mixto'), ('OTHER', 'Otro')], max_length=30, null=True, verbose_name='Tipo tecnología')),
                ('biomedical_classification', models.CharField(blank=True, max_length=50, verbose_name='Clasificación biomédica')),
                ('risk_class', models.CharField(blank=True, choices=[('I', 'Clase I — riesgo bajo'), ('IIA', 'Clase IIA — riesgo moderado'), ('IIB', 'Clase IIB — riesgo moderado-alto'), ('III', 'Clase III — riesgo alto')], db_index=True, max_length=4, null=True, verbose_name='Clasificación de riesgo INVIMA')),
                ('life_use_years', models.PositiveIntegerField(null=True, verbose_name='Vida útil (años)')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='Propietario')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Fabricante')),
                ('calibration_date', models.CharField(blank=True, max_length=50, verbose_name='Código de calibración')),
                ('client_name', models.CharField(blank=True, max_length=180, verbose_name='Cliente')),
                ('department', models.CharField(blank=True, max_length=80, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='Área')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ubicación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('supplier_acquisition', models.CharField(blank=True, max_length=150, verbose_name='Proveedor de adquisión')),
                ('start_use_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicia funcionamiento')),
                ('equipment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Costo equipo')),
                ('maintenance_provider', models.CharField(blank=True, max_length=150, verbose_name='Proveedor de mantenimiento')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicia garantía')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha finaliza garantía')),
                ('calibration_frequency_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia calibración (meses)')),
                ('maintenance_frequency_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia mantenimiento (meses)')),
                ('ecri', models.CharField(blank=True, max_length=80, verbose_name='ECRI')),
                ('invima_registration', models.CharField(blank=True, max_length=80, verbose_name='Registro Invima')),
                ('electrical_safety_class', models.CharField(blank=True, max_length=80, verbose_name='Clase seguridad eléctrica')),
                ('electrical_safety_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo seguridad eléctrica')),
                ('status', models.CharField(choices=[('ACTIVE', 'Operativo'), ('INACTIVE', 'Fuera de servicio'), ('IN_MAINTENANCE', 'En mantenimiento'), ('IN_REPAIR', 'En reparación')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('last_calibration', models.CharField(blank=True, max_length=120, verbose_name='Última calibración')),
                ('last_preventive', models.CharField(blank=True, max_length=120, verbose_name='Último preventivo')),
                ('next_preventive', models.CharField(blank=True, max_length=120, verbose_name='Próximo preventivo')),
                ('next_calibration', models.CharField(blank=True, max_length=120, verbose_name='Próxima calibración')),
                ('corrective_count', models.PositiveIntegerField(default=0, verbose_name='Número de correctivos.')),
                ('qr_code', models.FileField(blank=True, upload_to='equipment/qr/', verbose_name='Código QR')),
                ('equipment_image', models.ImageField(blank=True, null=True, upload_to='equipment/image', verbose_name='Imagen del equipo')),
                ('life_sheet_pdf', models.FileField(blank=True, upload_to='equipment/life_sheet', verbose_name='Hoja Vida PDF')),
                ('mtbf_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo promedio entre fallas consecutivas. Recalculado automáticamente.', max_digits=10, null=True, verbose_name='MTBF (horas)')),
                ('mttr_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo promedio para resolver una falla. Recalculado automáticamente.', max_digits=10, null=True, verbose_name='MTTR (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='branches.branch', verbose_name='Sede')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='catalog.equipmentmodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Equipo biomédico',
                'verbose_name_plural': 'Equipos biomédicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('LIFE_SHEET', 'Hoja de Vida'), ('MANUAL', 'Manual'), ('PHOTO', 'Fotografía'), ('CERTIFICATE', 'Certificado'), ('WARRANTY', 'Garantía'), ('PURCHASE', 'Compra'), ('OTHER', 'Otro')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='equipment/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipment.equipment')),
            ],
        ),
    ]
