# Generated by Django 5.0.6 on 2026-08-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentcertificate',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentinstruction',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordercost',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='equipment.equipmentworkorder'),
        ),
        migrations.AddField(
            model_name='workorderevidence',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='equipment.equipmentworkorder'),
        ),
        migrations.AddField(
            model_name='workordermeasurement',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentworkorder'),
        ),
        migrations.AddField(
            model_name='workordersignature',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='equipment.equipmentworkorder'),
        ),
        migrations.AddField(
            model_name='workordersparepart',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='equipment.equipmentworkorder'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_tag'], name='equipment_asset_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['branch'], name='equipment_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_model'], name='equipment_model_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['risk_class'], name='equipment_risk_class_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial'], name='equipment_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['software_identifier'], name='equipment_sw_id_idx'),
        ),
    ]
