# Generated by Django 5.0.6 on 2026-09-08 20:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentworkorder_maintenance_record'),
        ('maintenance', '0004_alter_maintenancerecord_assigned_technician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('description', models.TextField(verbose_name='Actividad realizada')),
                ('findings', models.TextField(blank=True, verbose_name='Hallazgos / diagnóstico encontrado')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('hourmeter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horómetro / kilometraje')),
                ('equipment_status_after', models.CharField(blank=True, choices=[('ACTIVE', 'Operativo'), ('INACTIVE', 'Fuera de servicio'), ('IN_MAINTENANCE', 'En mantenimiento'), ('IN_REPAIR', 'En reparación')], max_length=20, verbose_name='Estado operativo del equipo tras la intervención')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad de orden de trabajo',
                'verbose_name_plural': 'Actividades de orden de trabajo',
                'ordering': ['performed_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobada el'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada el'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerrada el'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por'),
        ),
        migrations.AddField(
            model_name='equipmentworkorder',
            name='closing_notes',
            field=models.TextField(blank=True, verbose_name='Observaciones de cierre'),
        ),
        migrations.AlterField(
            model_name='equipmentworkorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('IN_PROGRESS', 'En proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipmentworkorder',
            index=models.Index(fields=['status'], name='workorder_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentworkorder',
            index=models.Index(fields=['equipment', '-start_date'], name='workorder_eq_date_idx'),
        ),
        migrations.AddField(
            model_name='workorderactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='workorderactivity',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='equipment.equipmentworkorder', verbose_name='Orden de trabajo'),
        ),
        migrations.AddIndex(
            model_name='workorderactivity',
            index=models.Index(fields=['work_order', 'performed_at'], name='wo_activity_wo_date_idx'),
        ),
    ]
