# Generated by Django 5.0.6 on 2026-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_workorderactivity_equipmentworkorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Próxima Calibración'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_preventive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Próximo Preventivo'),
        ),
    ]
