# Generated by Django 5.0.6 on 2026-08-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10, verbose_name='Acción')),
                ('model_label', models.CharField(max_length=100, verbose_name='Modelo')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID del objeto')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Representación')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_label', 'object_id'], name='audit_model_object_idx'), models.Index(fields=['created_at'], name='audit_created_at_idx')],
            },
        ),
    ]
