# Generated by Django 5.0.6 on 2026-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('approve', 'Aprobación'), ('close', 'Cierre'), ('cancel', 'Cancelación')], max_length=10, verbose_name='Acción'),
        ),
    ]
