# Generated by Django 5.0.6 on 2026-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentworkorder_maintenance_record'),
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='failurerecord',
            constraint=models.CheckConstraint(check=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('reported_at')), _connector='OR'), name='failure_resolved_at_after_reported_at'),
        ),
    ]
