# Generated by Django 5.0.6 on 2026-09-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_workorderactivity_equipmentworkorder_approved_at_and_more'),
        ('failures', '0002_failurerecord_failure_resolved_at_after_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurerecord',
            name='corrective_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_failures', to='equipment.equipmentworkorder', verbose_name='Orden correctiva'),
        ),
    ]
