# Generated by Django 5.0.6 on 2026-08-11 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la sede.', max_length=120, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(db_index=True, max_length=80, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El teléfono no tiene un formato válido.', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='branch_name_idx'), models.Index(fields=['city'], name='branch_city_idx'), models.Index(fields=['is_active'], name='branch_is_active_idx')],
            },
        ),
    ]
