# Generated by Django 5.0.6 on 2026-09-06 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='La dirección no es válida', regex='^[\\w\\s.,#-]{5,200}$')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(code='Correo electrónico inválido', message='El correo electrónico no es válido')], verbose_name='Correo electrónico'),
        ),
    ]
