# Generated by Django 5.0.6 on 2026-08-11 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PREVENTIVE', 'Mantenimiento preventivo'), ('CORRECTIVE', 'Mantenimiento correctivo'), ('REPAIR', 'Reparación mayor'), ('CALIBRATION', 'Calibración'), ('INSPECTION', 'Inspection')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technician', models.CharField(blank=True, max_length=120, verbose_name='Técnico')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('pdf_file', models.FileField(blank=True, upload_to='maintenance/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CALIBRATION', 'Calibración'), ('INSPECTION', 'INSPECTION')], max_length=30, verbose_name='Tipo de mantenimiento')),
                ('frequency_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Frecuencia (meses)')),
                ('last_execution_date', models.DateField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_execution_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Próxima ejecución')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('iNACTIVE', 'Inactiva')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment', verbose_name='Equipo')),
            ],
            options={
                'ordering': ['next_execution_date'],
            },
        ),
    ]
