# Generated by Django 5.0.6 on 2026-08-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('maintenance', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'ingeniero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_records', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero asignado'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_records', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='scheduled_maintenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_record', to='scheduling.maintenanceschedule', verbose_name='Agendamiento cumplido'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmaintenanceschedule',
            constraint=models.UniqueConstraint(fields=('equipment', 'schedule_type'), name='unique_equipment_schedule_type'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', '-date'], name='maint_eq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['kind'], name='maint_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['date'], name='maint_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['assigned_engineer'], name='maint_engineer_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['assigned_technician'], name='maint_technician_idx'),
        ),
    ]
