# Generated by Django 5.0.6 on 2026-09-07 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancerecord_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'ingeniero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_records', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de ejecución'),
        ),
    ]
