# Generated by Django 5.0.6 on 2026-09-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador del Sistema'), ('coordinador', 'Coordinador Biomédico'), ('ingeniero', 'Ingeniero Biomédico'), ('tecnico', 'Técnico Biomédico'), ('usuario', 'Usuario Operativo'), ('auditor', 'Auditor de Calidad')], default='tecnico', max_length=20, verbose_name='Rol'),
        ),
    ]
