# Generated by Django 5.0.6 on 2026-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'SuperAdministrador del Sistema'), ('coordinador', 'Coordinador Biomédico'), ('ingeniero', 'Ingeniero Biomédico'), ('usuario', 'Usuario Operativo')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
