# Generated by Django 5.0.6 on 2026-09-09 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_next_calibration_date_and_more'),
        ('scheduling', '0003_alter_maintenanceschedule_assigned_technician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Generado automáticamente'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='generated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollovers', to='scheduling.maintenanceschedule', verbose_name='Generado a partir de'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='kind',
            field=models.CharField(choices=[('PREVENTIVE', 'Mantenimiento preventivo'), ('CALIBRATION', 'Calibración / aseguramiento metrológico'), ('REPAIR', 'Reparación programada')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DUE_SOON', 'Próximo a vencer'), ('OVERDUE', 'Vencido')], db_index=True, max_length=20, verbose_name='Tipo de alerta')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generada el')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Atendida el')),
                ('acknowledgement_note', models.TextField(blank=True, verbose_name='Nota de atención')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='equipment.equipment', verbose_name='Equipo')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scheduling.maintenanceschedule', verbose_name='Agendamiento')),
            ],
            options={
                'verbose_name': 'Alerta de mantenimiento',
                'verbose_name_plural': 'Alertas de mantenimiento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', '-created_at'], name='alert_eq_created_idx'), models.Index(fields=['acknowledged_at'], name='alert_ack_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancealert',
            constraint=models.UniqueConstraint(condition=models.Q(('acknowledged_at__isnull', True)), fields=('schedule', 'alert_type'), name='uniq_open_alert_per_schedule_type'),
        ),
    ]
